2013-11-13 Claudiu Zissulescu <claziss@synopsys.com>

	* arc.h (ARC_MACH_ARCV2HS): Define.

2011-05-17  Brendan Kehoe  <brendan@zen.org>

	* arc.h (AC_SUFFIX_DIRECT): Define.

2010-07-27  Michael Eager  <eager@eagercon.com>

	* arc.h: New ARC_MACH_ARC601.
	
2009-09-07  Irfan Rafiq  <irfan.rafiq@arc.com>

	* cgen.h (struct cgen_cpu_desc) <dis_hash>: Update parameter list.

2008-11-14  Irfan Rafiq  <irfan.rafiq@arc.com>
        * arc.h:		 Sync with processor info.

        
        
