2014-09-12  Andrew Burgess  <andrew.burgess@embecosm.com>

	* ld-arc/arc.exp: New file.
	* ld-arc/dummy-lib.s: New file.
	* ld-arc/gotpc1.d: New file.
	* ld-arc/gotpc1.ld: New file.
	* ld-arc/gotpc1.s: New file.
	* ld-arc/gotpc2.d: New file.
	* ld-arc/gotpc2.ld: New file.

2014-09-22  Andrew Burgess  <andrew.burgess@embecosm.com>

	* ld-arc/arc.exp: New file.
	* ld-arc/gc-sections1.d: New file.
	* ld-arc/gc-sections1.s: New file.
	* ld-arc/gc-sections1.ver: New file.
