/* Target dependent code for ARC processor family, for GDB, the GNU debugger.

   Copyright 2005 Free Software Foundation, Inc.
   Copyright 2009-2012 Synopsys Inc.

   Contributed by Codito Technologies Pvt. Ltd. (www.codito.com) on behalf of
   Synopsys Inc.

   Authors: 
      Sameer Dhavale  <sameer.dhavale@codito.com>
      Soam Vasani     <soam.vasani@codito.com>
      Richard Stuckey <richard.stuckey@arc.com>

   This file is part of GDB.
   
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  
*/

/******************************************************************************/
/*                                                                            */
/* Outline:                                                                   */
/*     This header file defines the JTAG interface to an ARC processor.       */
/*                                                                            */
/*     Operations are provided for:                                           */
/*        1) controlling the interface                                        */
/*        2) reading/writing the core registers of the processor              */
/*        3) reading/writing the auxiliary registers of the processor         */
/*        4) reading/writing single words in the target memory                */
/*        5) reading/writing blocks in the target memory                      */
/*                                                                            */
/*     The addresses specified for the memory word read/write operations must */
/*     be word-aligned.  Those specified for the memory block read/write      */
/*     operations may have any alignment; these operations may transfer an    */
/*     arbitrary number of bytes.                                             */
/*                                                                            */
/* Usage:                                                                     */
/*     The module exports a global variable arc_jtag_ops which holds pointers */
/*     to the functions for the operations, as well as some state information.*/
/*     This variable is initialized by the function _initialize_arc_jtag_ops  */
/*     which must be called before any use is made of the module (N.B. the    */
/*     call to this function is generated by the gdb build mechanism, so this */
/*     function should not be explicitly called).                             */
/*                                                                            */
/*     The variable arc_jtag_ops.retry_count controls how many repeated       */
/*     attempts are made if a read/write operation fail; this variable is     */
/*     initially set to 50.                                                   */
/*                                                                            */
/* Debugging facilities:                                                      */
/*     If the variable arc_jtag_ops.state_machine_debug is set to TRUE then   */
/*     trace information will be output.                                      */
/*                                                                            */
/******************************************************************************/

#ifndef ARC_JTAG_OPS
#define ARC_JTAG_OPS

/* ARC header files */
#include "arc-support.h"


#define ARC_TARGET_NAME     "arcjtag"


typedef enum
{
    JTAG_SUCCESS,
    JTAG_READ_FAILURE,
    JTAG_WRITE_FAILURE
} JTAG_OperationStatus;


typedef enum
{
    JTAG_OPENED,
    JTAG_CLOSED
} JTAG_Status;


typedef struct
{
    JTAG_Status  status;
    unsigned int retry_count;
    Boolean      state_machine_debug;

    Boolean (*open)        (void);
    void    (*close)       (void);
    void    (*reset)       (void);
    void    (*reset_board) (void);
    void    (*check_open)  (void);

    /* these operations return the number of bytes read/written */
    unsigned int (*memory_read_word)     (ARC_Address addr, ARC_Word* data);                          // single word
    unsigned int (*memory_write_word)    (ARC_Address addr, ARC_Word  data);                          // single word
    unsigned int (*memory_read_chunk)    (ARC_Address addr, ARC_Byte* data,    unsigned int bytes);   // block
    unsigned int (*memory_write_chunk)   (ARC_Address addr, ARC_Byte* data,    unsigned int bytes);   // block
    unsigned int (*memory_write_pattern) (ARC_Address addr, ARC_Word  pattern, unsigned int bytes);   // block

    /* an operation to fill a chunk of memory with zeroes */
#define memory_zero_fill(addr, len)     memory_write_pattern(addr, 0, len)

    JTAG_OperationStatus (*read_aux_reg)   (ARC_RegisterNumber reg, ARC_RegisterContents* contents);
    JTAG_OperationStatus (*write_aux_reg)  (ARC_RegisterNumber reg, ARC_RegisterContents  contents);
    JTAG_OperationStatus (*read_core_reg)  (ARC_RegisterNumber reg, ARC_RegisterContents* contents);
    JTAG_OperationStatus (*write_core_reg) (ARC_RegisterNumber reg, ARC_RegisterContents  contents);
} JTAG_Operations;


extern JTAG_Operations arc_jtag_ops;


void _initialize_arc_jtag_ops (void);


#endif /* ARC_JTAG_OPS */
/******************************************************************************/
