2013-01-08  Jeremy Bennett <jeremy.bennett@embecosm.com>

	* common/gennltvals.sh: Add "arc" as a target.
	* common/nltvals.sh: Regenerated.

2012-12-13  Jeremy Bennett <jeremy.bennett@embecosm.com>

	* configure: Regenerated
	* configure.tgt: Add arc*-*-* as new target.

2012-12-12  Jeremy Bennett <jeremy.bennett@embecosm.com>

	Manual merge from GDB 6.8 branch.

	* arc: Merged as new directory.
