SCRIPT_NAME=elf
ELFSIZE=64
TEMPLATE_NAME=elf32
OUTPUT_FORMAT="elf64-littlearc"

TEXT_START_ADDR=0x00

MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH=arc
ENTRY=__start
EMBEDDED=yes

GENERATE_SHLIB_SCRIPT=yes
EXTRA_EM_FILE=arcelf
