.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vmv.v.s v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmv.v.s v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmv.v.s v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmv.s.v v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmv.s.v v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmv.s.v v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.v.s v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.v.s v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.v.s v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.s.v v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.s.v v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vmvi.s.v v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnorm.v v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnorm.v v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vssabs.v v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vssabs.v v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsneg.v v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsneg.v v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vclr.v.i v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vclr.v.i v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.vi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsrat.vi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.s.vi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsra.2s.vi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.wi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.wi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.wi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.qi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.s.qi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vnsra.2s.qi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vi v0,v3,6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vi v3,v6,0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsra.vi v6,v0,3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vaddsub.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vaddsub.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vaddsub.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaddsub.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaddsub.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaddsub.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaaddsub.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaaddsub.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsaaddsub.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.2s.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.2s.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdot.2s.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.2s.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.2s.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.2s.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotu.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotu.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotu.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotsu.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotsu.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vqrdotsu.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdot.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotsu.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotsu.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotsu.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmac.vx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsac.vx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmul.hx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmac.hx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulu.hx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmacu.hx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdot.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwrdotu.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vsmulf.hx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hx v0,v3,t6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hx v3,v6,t0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwmulf.hx v6,v0,t3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsmacf.hx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hx v0,t3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hx v3,t6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsnmsacf.hx v6,t0,v3', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdotf.hv v0,v3,v6', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdotf.hv v3,v6,v0', extension `xarcvvdsp' required
.*: Error: unrecognized opcode `arcv.vwsrdotf.hv v6,v0,v3', extension `xarcvvdsp' required
.*: Error: illegal operands `arcv.vmv.v.s v0,v3'
.*: Error: illegal operands `arcv.vmv.v.s v3,v6'
.*: Error: illegal operands `arcv.vmv.v.s v6,v0'
.*: Error: illegal operands `arcv.vmv.s.v v0,v3'
.*: Error: illegal operands `arcv.vmv.s.v v3,v6'
.*: Error: illegal operands `arcv.vmv.s.v v6,v0'
.*: Error: illegal operands `arcv.vmvi.v.s v0,v3'
.*: Error: illegal operands `arcv.vmvi.v.s v3,v6'
.*: Error: illegal operands `arcv.vmvi.v.s v6,v0'
.*: Error: illegal operands `arcv.vmvi.s.v v0,v3'
.*: Error: illegal operands `arcv.vmvi.s.v v3,v6'
.*: Error: illegal operands `arcv.vmvi.s.v v6,v0'
.*: Error: illegal operands `arcv.vnorm.v v0'
.*: Error: illegal operands `arcv.vnorm.v v3'
.*: Error: illegal operands `arcv.vssabs.v v0'
.*: Error: illegal operands `arcv.vssabs.v v3'
.*: Error: illegal operands `arcv.vsneg.v v0'
.*: Error: illegal operands `arcv.vsneg.v v3'
.*: Error: illegal operands `arcv.vclr.v.i v0'
.*: Error: illegal operands `arcv.vclr.v.i v3'
.*: Error: illegal operands `arcv.vsra.vv v0,v3'
.*: Error: illegal operands `arcv.vsra.vv v3,v6'
.*: Error: illegal operands `arcv.vsra.vv v6,v0'
.*: Error: illegal operands `arcv.vsra.vx v0,v3'
.*: Error: illegal operands `arcv.vsra.vx v3,v6'
.*: Error: illegal operands `arcv.vsra.vx v6,v0'
.*: Error: illegal operands `arcv.vsra.vi v0,v3'
.*: Error: illegal operands `arcv.vsra.vi v3,v6'
.*: Error: illegal operands `arcv.vsra.vi v6,v0'
.*: Error: illegal operands `arcv.vsrat.vv v0,v3'
.*: Error: illegal operands `arcv.vsrat.vv v3,v6'
.*: Error: illegal operands `arcv.vsrat.vv v6,v0'
.*: Error: illegal operands `arcv.vsrat.vx v0,v3'
.*: Error: illegal operands `arcv.vsrat.vx v3,v6'
.*: Error: illegal operands `arcv.vsrat.vx v6,v0'
.*: Error: illegal operands `arcv.vsrat.vi v0,v3'
.*: Error: illegal operands `arcv.vsrat.vi v3,v6'
.*: Error: illegal operands `arcv.vsrat.vi v6,v0'
.*: Error: illegal operands `arcv.vsra.s.vv v0,v3'
.*: Error: illegal operands `arcv.vsra.s.vv v3,v6'
.*: Error: illegal operands `arcv.vsra.s.vv v6,v0'
.*: Error: illegal operands `arcv.vsra.s.vx v0,v3'
.*: Error: illegal operands `arcv.vsra.s.vx v3,v6'
.*: Error: illegal operands `arcv.vsra.s.vx v6,v0'
.*: Error: illegal operands `arcv.vsra.s.vi v0,v3'
.*: Error: illegal operands `arcv.vsra.s.vi v3,v6'
.*: Error: illegal operands `arcv.vsra.s.vi v6,v0'
.*: Error: illegal operands `arcv.vsra.2s.vv v0,v3'
.*: Error: illegal operands `arcv.vsra.2s.vv v3,v6'
.*: Error: illegal operands `arcv.vsra.2s.vv v6,v0'
.*: Error: illegal operands `arcv.vsra.2s.vx v0,v3'
.*: Error: illegal operands `arcv.vsra.2s.vx v3,v6'
.*: Error: illegal operands `arcv.vsra.2s.vx v6,v0'
.*: Error: illegal operands `arcv.vsra.2s.vi v0,v3'
.*: Error: illegal operands `arcv.vsra.2s.vi v3,v6'
.*: Error: illegal operands `arcv.vsra.2s.vi v6,v0'
.*: Error: illegal operands `arcv.vnsra.wv v0,v3'
.*: Error: illegal operands `arcv.vnsra.wv v3,v6'
.*: Error: illegal operands `arcv.vnsra.wv v6,v0'
.*: Error: illegal operands `arcv.vnsra.wx v0,v3'
.*: Error: illegal operands `arcv.vnsra.wx v3,v6'
.*: Error: illegal operands `arcv.vnsra.wx v6,v0'
.*: Error: illegal operands `arcv.vnsra.wi v0,v3'
.*: Error: illegal operands `arcv.vnsra.wi v3,v6'
.*: Error: illegal operands `arcv.vnsra.wi v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.wv v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.wv v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.wv v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.wx v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.wx v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.wx v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.wi v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.wi v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.wi v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.wv v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.wv v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.wv v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.wx v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.wx v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.wx v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.wi v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.wi v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.wi v6,v0'
.*: Error: illegal operands `arcv.vnsra.qv v0,v3'
.*: Error: illegal operands `arcv.vnsra.qv v3,v6'
.*: Error: illegal operands `arcv.vnsra.qv v6,v0'
.*: Error: illegal operands `arcv.vnsra.qx v0,v3'
.*: Error: illegal operands `arcv.vnsra.qx v3,v6'
.*: Error: illegal operands `arcv.vnsra.qx v6,v0'
.*: Error: illegal operands `arcv.vnsra.qi v0,v3'
.*: Error: illegal operands `arcv.vnsra.qi v3,v6'
.*: Error: illegal operands `arcv.vnsra.qi v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.qv v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.qv v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.qv v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.qx v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.qx v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.qx v6,v0'
.*: Error: illegal operands `arcv.vnsra.s.qi v0,v3'
.*: Error: illegal operands `arcv.vnsra.s.qi v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.qi v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.qv v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.qv v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.qv v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.qx v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.qx v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.qx v6,v0'
.*: Error: illegal operands `arcv.vnsra.2s.qi v0,v3'
.*: Error: illegal operands `arcv.vnsra.2s.qi v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.qi v6,v0'
.*: Error: illegal operands `arcv.vwsra.vv v0,v3'
.*: Error: illegal operands `arcv.vwsra.vv v3,v6'
.*: Error: illegal operands `arcv.vwsra.vv v6,v0'
.*: Error: illegal operands `arcv.vwsra.vx v0,v3'
.*: Error: illegal operands `arcv.vwsra.vx v3,v6'
.*: Error: illegal operands `arcv.vwsra.vx v6,v0'
.*: Error: illegal operands `arcv.vwsra.vi v0,v3'
.*: Error: illegal operands `arcv.vwsra.vi v3,v6'
.*: Error: illegal operands `arcv.vwsra.vi v6,v0'
.*: Error: illegal operands `arcv.vaddsub.vv v0,v3'
.*: Error: illegal operands `arcv.vaddsub.vv v3,v6'
.*: Error: illegal operands `arcv.vaddsub.vv v6,v0'
.*: Error: illegal operands `arcv.vsaddsub.vv v0,v3'
.*: Error: illegal operands `arcv.vsaddsub.vv v3,v6'
.*: Error: illegal operands `arcv.vsaddsub.vv v6,v0'
.*: Error: illegal operands `arcv.vsaaddsub.vv v0,v3'
.*: Error: illegal operands `arcv.vsaaddsub.vv v3,v6'
.*: Error: illegal operands `arcv.vsaaddsub.vv v6,v0'
.*: Error: illegal operands `arcv.vqrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vqrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vqrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v0,v3'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v3,v6'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v6,v0'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v0,v3'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v3,v6'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v6,v0'
.*: Error: illegal operands `arcv.vqrdotu.vv v0,v3'
.*: Error: illegal operands `arcv.vqrdotu.vv v3,v6'
.*: Error: illegal operands `arcv.vqrdotu.vv v6,v0'
.*: Error: illegal operands `arcv.vqrdotsu.vv v0,v3'
.*: Error: illegal operands `arcv.vqrdotsu.vv v3,v6'
.*: Error: illegal operands `arcv.vqrdotsu.vv v6,v0'
.*: Error: illegal operands `arcv.vwrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vwrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vwrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vwsrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vwsrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vwsrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vwrdotu.vv v0,v3'
.*: Error: illegal operands `arcv.vwrdotu.vv v3,v6'
.*: Error: illegal operands `arcv.vwrdotu.vv v6,v0'
.*: Error: illegal operands `arcv.vwrdotsu.vv v0,v3'
.*: Error: illegal operands `arcv.vwrdotsu.vv v3,v6'
.*: Error: illegal operands `arcv.vwrdotsu.vv v6,v0'
.*: Error: illegal operands `arcv.vwsmac.vv v0,v3'
.*: Error: illegal operands `arcv.vwsmac.vv v3,v6'
.*: Error: illegal operands `arcv.vwsmac.vv v6,v0'
.*: Error: illegal operands `arcv.vwsmac.vx v0,v3'
.*: Error: illegal operands `arcv.vwsmac.vx v3,v6'
.*: Error: illegal operands `arcv.vwsmac.vx v6,v0'
.*: Error: illegal operands `arcv.vwsnmsac.vv v0,v3'
.*: Error: illegal operands `arcv.vwsnmsac.vv v3,v6'
.*: Error: illegal operands `arcv.vwsnmsac.vv v6,v0'
.*: Error: illegal operands `arcv.vwsnmsac.vx v0,v3'
.*: Error: illegal operands `arcv.vwsnmsac.vx v3,v6'
.*: Error: illegal operands `arcv.vwsnmsac.vx v6,v0'
.*: Error: illegal operands `arcv.vwmul.hv v0,v3'
.*: Error: illegal operands `arcv.vwmul.hv v3,v6'
.*: Error: illegal operands `arcv.vwmul.hv v6,v0'
.*: Error: illegal operands `arcv.vwmul.hx v0,v3'
.*: Error: illegal operands `arcv.vwmul.hx v3,v6'
.*: Error: illegal operands `arcv.vwmul.hx v6,v0'
.*: Error: illegal operands `arcv.vwmac.hv v0,v3'
.*: Error: illegal operands `arcv.vwmac.hv v3,v6'
.*: Error: illegal operands `arcv.vwmac.hv v6,v0'
.*: Error: illegal operands `arcv.vwmac.hx v0,v3'
.*: Error: illegal operands `arcv.vwmac.hx v3,v6'
.*: Error: illegal operands `arcv.vwmac.hx v6,v0'
.*: Error: illegal operands `arcv.vwmulu.hv v0,v3'
.*: Error: illegal operands `arcv.vwmulu.hv v3,v6'
.*: Error: illegal operands `arcv.vwmulu.hv v6,v0'
.*: Error: illegal operands `arcv.vwmulu.hx v0,v3'
.*: Error: illegal operands `arcv.vwmulu.hx v3,v6'
.*: Error: illegal operands `arcv.vwmulu.hx v6,v0'
.*: Error: illegal operands `arcv.vwmacu.hv v0,v3'
.*: Error: illegal operands `arcv.vwmacu.hv v3,v6'
.*: Error: illegal operands `arcv.vwmacu.hv v6,v0'
.*: Error: illegal operands `arcv.vwmacu.hx v0,v3'
.*: Error: illegal operands `arcv.vwmacu.hx v3,v6'
.*: Error: illegal operands `arcv.vwmacu.hx v6,v0'
.*: Error: illegal operands `arcv.vwrdot.hv v0,v3'
.*: Error: illegal operands `arcv.vwrdot.hv v3,v6'
.*: Error: illegal operands `arcv.vwrdot.hv v6,v0'
.*: Error: illegal operands `arcv.vwrdotu.hv v0,v3'
.*: Error: illegal operands `arcv.vwrdotu.hv v3,v6'
.*: Error: illegal operands `arcv.vwrdotu.hv v6,v0'
.*: Error: illegal operands `arcv.vsmulf.hv v0,v3'
.*: Error: illegal operands `arcv.vsmulf.hv v3,v6'
.*: Error: illegal operands `arcv.vsmulf.hv v6,v0'
.*: Error: illegal operands `arcv.vsmulf.hx v0,v3'
.*: Error: illegal operands `arcv.vsmulf.hx v3,v6'
.*: Error: illegal operands `arcv.vsmulf.hx v6,v0'
.*: Error: illegal operands `arcv.vwmulf.hv v0,v3'
.*: Error: illegal operands `arcv.vwmulf.hv v3,v6'
.*: Error: illegal operands `arcv.vwmulf.hv v6,v0'
.*: Error: illegal operands `arcv.vwmulf.hx v0,v3'
.*: Error: illegal operands `arcv.vwmulf.hx v3,v6'
.*: Error: illegal operands `arcv.vwmulf.hx v6,v0'
.*: Error: illegal operands `arcv.vwsmacf.hv v0,v3'
.*: Error: illegal operands `arcv.vwsmacf.hv v3,v6'
.*: Error: illegal operands `arcv.vwsmacf.hv v6,v0'
.*: Error: illegal operands `arcv.vwsmacf.hx v0,v3'
.*: Error: illegal operands `arcv.vwsmacf.hx v3,v6'
.*: Error: illegal operands `arcv.vwsmacf.hx v6,v0'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v0,v3'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v3,v6'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v6,v0'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v0,v3'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v3,v6'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v6,v0'
.*: Error: illegal operands `arcv.vwsrdotf.hv v0,v3'
.*: Error: illegal operands `arcv.vwsrdotf.hv v3,v6'
.*: Error: illegal operands `arcv.vwsrdotf.hv v6,v0'
.*: Error: illegal operands `arcv.vmv.v.s v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vmv.v.s v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vmv.v.s v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vmv.s.v v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vmv.s.v v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vmv.s.v v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vmvi.v.s v0,v3,6,t0'
.*: Error: illegal operands `arcv.vmvi.v.s v3,v6,0,t0'
.*: Error: illegal operands `arcv.vmvi.v.s v6,v0,3,t0'
.*: Error: illegal operands `arcv.vmvi.s.v v0,v3,6,t0'
.*: Error: illegal operands `arcv.vmvi.s.v v3,v6,0,t0'
.*: Error: illegal operands `arcv.vmvi.s.v v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnorm.v v0,v3,t0'
.*: Error: illegal operands `arcv.vnorm.v v3,v6,t0'
.*: Error: illegal operands `arcv.vssabs.v v0,v3,t0'
.*: Error: illegal operands `arcv.vssabs.v v3,v6,t0'
.*: Error: illegal operands `arcv.vsneg.v v0,v3,t0'
.*: Error: illegal operands `arcv.vsneg.v v3,v6,t0'
.*: Error: illegal operands `arcv.vclr.v.i v0,3,t0'
.*: Error: illegal operands `arcv.vclr.v.i v3,6,t0'
.*: Error: illegal operands `arcv.vsra.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsra.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsra.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsra.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vsra.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vsra.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vsra.vi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vsra.vi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vsra.vi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vsrat.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsrat.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsrat.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsrat.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vsrat.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vsrat.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vsrat.vi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vsrat.vi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vsrat.vi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vsra.s.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsra.s.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsra.s.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsra.s.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vsra.s.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vsra.s.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vsra.s.vi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vsra.s.vi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vsra.s.vi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vsra.2s.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsra.2s.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsra.2s.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsra.2s.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vsra.2s.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vsra.2s.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vsra.2s.vi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vsra.2s.vi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vsra.2s.vi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.wv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.wv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.wv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.wx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.wx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.wx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.wi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.wi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.wi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.s.wv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.s.wv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.s.wv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.s.wx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.s.wx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.s.wx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.s.wi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.s.wi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.s.wi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.wi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.qv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.qv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.qv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.qx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.qx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.qx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.qi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.qi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.qi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.s.qv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.s.qv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.s.qv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.s.qx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.s.qx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.s.qx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.s.qi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.s.qi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.s.qi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vnsra.2s.qi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vwsra.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsra.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsra.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsra.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwsra.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwsra.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwsra.vi v0,v3,6,t0'
.*: Error: illegal operands `arcv.vwsra.vi v3,v6,0,t0'
.*: Error: illegal operands `arcv.vwsra.vi v6,v0,3,t0'
.*: Error: illegal operands `arcv.vaddsub.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vaddsub.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vaddsub.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsaddsub.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsaddsub.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsaddsub.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsaaddsub.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsaaddsub.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsaaddsub.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqrdotu.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqrdotu.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqrdotu.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqrdotsu.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqrdotsu.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqrdotsu.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwrdotu.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwrdotu.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwrdotu.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwrdotsu.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwrdotsu.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwrdotsu.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsmac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsmac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsmac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsmac.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwsmac.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwsmac.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwsnmsac.vx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwmul.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwmul.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwmul.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwmul.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwmul.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwmul.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwmac.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwmac.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwmac.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwmac.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwmac.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwmac.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwmulu.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwmulu.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwmulu.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwmulu.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwmulu.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwmulu.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwmacu.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwmacu.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwmacu.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwmacu.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwmacu.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwmacu.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwrdot.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwrdot.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwrdot.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwrdotu.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwrdotu.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwrdotu.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsmulf.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vsmulf.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vsmulf.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vsmulf.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vsmulf.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vsmulf.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwmulf.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwmulf.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwmulf.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwmulf.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwmulf.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwmulf.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwsmacf.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsmacf.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsmacf.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsmacf.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwsmacf.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwsmacf.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v0,v3,t6,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v3,v6,t0,t0'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v6,v0,t3,t0'
.*: Error: illegal operands `arcv.vwsrdotf.hv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsrdotf.hv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsrdotf.hv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vmv.v.s 0,v3,t6'
.*: Error: illegal operands `arcv.vmv.v.s v0,3,t6'
.*: Error: illegal operands `arcv.vmv.v.s v0,v3,6'
.*: Error: illegal operands `arcv.vmv.s.v 0,v3,t6'
.*: Error: illegal operands `arcv.vmv.s.v v0,3,t6'
.*: Error: illegal operands `arcv.vmv.s.v v0,v3,6'
.*: Error: illegal operands `arcv.vmvi.v.s 0,v3,6'
.*: Error: illegal operands `arcv.vmvi.v.s v0,3,6'
.*: Error: instruction arcv.vmvi.v.s requires absolute expression
.*: Error: illegal operands `arcv.vmvi.s.v 0,v3,6'
.*: Error: illegal operands `arcv.vmvi.s.v v0,3,6'
.*: Error: instruction arcv.vmvi.s.v requires absolute expression
.*: Error: illegal operands `arcv.vnorm.v 0,v3'
.*: Error: illegal operands `arcv.vnorm.v v0,3'
.*: Error: illegal operands `arcv.vssabs.v 0,v3'
.*: Error: illegal operands `arcv.vssabs.v v0,3'
.*: Error: illegal operands `arcv.vsneg.v 0,v3'
.*: Error: illegal operands `arcv.vsneg.v v0,3'
.*: Error: illegal operands `arcv.vclr.v.i 0,3'
.*: Error: instruction arcv.vclr.v.i requires absolute expression
.*: Error: illegal operands `arcv.vsra.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsra.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsra.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsra.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vsra.vx v0,3,t6'
.*: Error: illegal operands `arcv.vsra.vx v0,v3,6'
.*: Error: illegal operands `arcv.vsra.vi 0,v3,6'
.*: Error: illegal operands `arcv.vsra.vi v0,3,6'
.*: Error: instruction arcv.vsra.vi requires absolute expression
.*: Error: illegal operands `arcv.vsrat.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsrat.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsrat.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsrat.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vsrat.vx v0,3,t6'
.*: Error: illegal operands `arcv.vsrat.vx v0,v3,6'
.*: Error: illegal operands `arcv.vsrat.vi 0,v3,6'
.*: Error: illegal operands `arcv.vsrat.vi v0,3,6'
.*: Error: instruction arcv.vsrat.vi requires absolute expression
.*: Error: illegal operands `arcv.vsra.s.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsra.s.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsra.s.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsra.s.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vsra.s.vx v0,3,t6'
.*: Error: illegal operands `arcv.vsra.s.vx v0,v3,6'
.*: Error: illegal operands `arcv.vsra.s.vi 0,v3,6'
.*: Error: illegal operands `arcv.vsra.s.vi v0,3,6'
.*: Error: instruction arcv.vsra.s.vi requires absolute expression
.*: Error: illegal operands `arcv.vsra.2s.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsra.2s.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsra.2s.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsra.2s.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vsra.2s.vx v0,3,t6'
.*: Error: illegal operands `arcv.vsra.2s.vx v0,v3,6'
.*: Error: illegal operands `arcv.vsra.2s.vi 0,v3,6'
.*: Error: illegal operands `arcv.vsra.2s.vi v0,3,6'
.*: Error: instruction arcv.vsra.2s.vi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.wv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.wv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.wv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.wx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.wx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.wx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.wi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.wi v0,3,6'
.*: Error: instruction arcv.vnsra.wi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.s.wv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.wv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.s.wv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.wx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.s.wx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.s.wx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.wi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.wi v0,3,6'
.*: Error: instruction arcv.vnsra.s.wi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.2s.wv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.wv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.wv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.wx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.2s.wx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.2s.wx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.wi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.wi v0,3,6'
.*: Error: instruction arcv.vnsra.2s.wi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.qv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.qv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.qv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.qx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.qx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.qx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.qi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.qi v0,3,6'
.*: Error: instruction arcv.vnsra.qi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.s.qv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.s.qv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.s.qv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.qx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.s.qx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.s.qx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.qi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.s.qi v0,3,6'
.*: Error: instruction arcv.vnsra.s.qi requires absolute expression
.*: Error: illegal operands `arcv.vnsra.2s.qv 0,v3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.qv v0,3,v6'
.*: Error: illegal operands `arcv.vnsra.2s.qv v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.qx 0,v3,t6'
.*: Error: illegal operands `arcv.vnsra.2s.qx v0,3,t6'
.*: Error: illegal operands `arcv.vnsra.2s.qx v0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.qi 0,v3,6'
.*: Error: illegal operands `arcv.vnsra.2s.qi v0,3,6'
.*: Error: instruction arcv.vnsra.2s.qi requires absolute expression
.*: Error: illegal operands `arcv.vwsra.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsra.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsra.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsra.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vwsra.vx v0,3,t6'
.*: Error: illegal operands `arcv.vwsra.vx v0,v3,6'
.*: Error: illegal operands `arcv.vwsra.vi 0,v3,6'
.*: Error: illegal operands `arcv.vwsra.vi v0,3,6'
.*: Error: instruction arcv.vwsra.vi requires absolute expression
.*: Error: illegal operands `arcv.vaddsub.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vaddsub.vv v0,3,v6'
.*: Error: illegal operands `arcv.vaddsub.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsaddsub.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsaddsub.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsaddsub.vv v0,v3,6'
.*: Error: illegal operands `arcv.vsaaddsub.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vsaaddsub.vv v0,3,v6'
.*: Error: illegal operands `arcv.vsaaddsub.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqrdot.2s.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqrdot.2s.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsrdot.2s.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqrdotu.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqrdotu.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqrdotu.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqrdotsu.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqrdotsu.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqrdotsu.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwrdotu.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwrdotu.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwrdotu.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwrdotsu.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwrdotsu.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwrdotsu.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsmac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsmac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsmac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsmac.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vwsmac.vx v0,3,t6'
.*: Error: illegal operands `arcv.vwsmac.vx v0,v3,6'
.*: Error: illegal operands `arcv.vwsnmsac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsnmsac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsnmsac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsnmsac.vx 0,v3,t6'
.*: Error: illegal operands `arcv.vwsnmsac.vx v0,3,t6'
.*: Error: illegal operands `arcv.vwsnmsac.vx v0,v3,6'
.*: Error: illegal operands `arcv.vwmul.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwmul.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwmul.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwmul.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwmul.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwmul.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwmac.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwmac.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwmac.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwmac.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwmac.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwmac.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwmulu.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwmulu.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwmulu.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwmulu.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwmulu.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwmulu.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwmacu.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwmacu.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwmacu.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwmacu.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwmacu.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwmacu.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwrdot.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwrdot.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwrdot.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwrdotu.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwrdotu.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwrdotu.hv v0,v3,6'
.*: Error: illegal operands `arcv.vsmulf.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vsmulf.hv v0,3,v6'
.*: Error: illegal operands `arcv.vsmulf.hv v0,v3,6'
.*: Error: illegal operands `arcv.vsmulf.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vsmulf.hx v0,3,t6'
.*: Error: illegal operands `arcv.vsmulf.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwmulf.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwmulf.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwmulf.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwmulf.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwmulf.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwmulf.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwsmacf.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsmacf.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwsmacf.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwsmacf.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwsmacf.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwsmacf.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwsnmsacf.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwsnmsacf.hv v0,v3,6'
.*: Error: illegal operands `arcv.vwsnmsacf.hx 0,v3,t6'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v0,3,t6'
.*: Error: illegal operands `arcv.vwsnmsacf.hx v0,v3,6'
.*: Error: illegal operands `arcv.vwsrdotf.hv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsrdotf.hv v0,3,v6'
.*: Error: illegal operands `arcv.vwsrdotf.hv v0,v3,6'
