.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vwsad.vv v0,v3,v6', extension `xarcvvsad' required
.*: Error: unrecognized opcode `arcv.vwsad.vv v3,v6,v0', extension `xarcvvsad' required
.*: Error: unrecognized opcode `arcv.vwsad.vv v6,v0,v3', extension `xarcvvsad' required
.*: Error: unrecognized opcode `arcv.vwsadu.vv v0,v3,v6', extension `xarcvvsad' required
.*: Error: unrecognized opcode `arcv.vwsadu.vv v3,v6,v0', extension `xarcvvsad' required
.*: Error: unrecognized opcode `arcv.vwsadu.vv v6,v0,v3', extension `xarcvvsad' required
.*: Error: illegal operands `arcv.vwsad.vv v0,v3'
.*: Error: illegal operands `arcv.vwsad.vv v3,v6'
.*: Error: illegal operands `arcv.vwsad.vv v6,v0'
.*: Error: illegal operands `arcv.vwsadu.vv v0,v3'
.*: Error: illegal operands `arcv.vwsadu.vv v3,v6'
.*: Error: illegal operands `arcv.vwsadu.vv v6,v0'
.*: Error: illegal operands `arcv.vwsad.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsad.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsad.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsadu.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwsadu.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwsadu.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwsad.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsad.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsad.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwsadu.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwsadu.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwsadu.vv v0,v3,6'
