.*: Assembler messages:
.*: Error: integer operand out of range; should be from -128 to 127, inclusive
.*: Error: unrecognized opcode `foo0'
.*: Error: integer operand out of range; should be from -128 to 127, inclusive
.*: Error: unrecognized opcode `foo0'
.*: Error: integer operand out of range; should be from -2048 to 2047, inclusive
.*: Error: integer operand out of range; should be from -2048 to 2047, inclusive
.*: Error: integer operand out of range; should be from -2048 to 2047, inclusive
.*: Error: integer operand out of range; should be from -2048 to 2047, inclusive
