.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.bitrev t0,t3,t6', extension `xarcvbitrev' required
.*: Error: unrecognized opcode `arcv.bitrev t3,t6,t0', extension `xarcvbitrev' required
.*: Error: unrecognized opcode `arcv.bitrev t6,t0,t3', extension `xarcvbitrev' required
.*: Error: illegal operands `arcv.bitrev t0,t3'
.*: Error: illegal operands `arcv.bitrev t3,t6'
.*: Error: illegal operands `arcv.bitrev t6,t0'
.*: Error: illegal operands `arcv.bitrev t0,t3,t6,t0'
.*: Error: illegal operands `arcv.bitrev t3,t6,t0,t0'
.*: Error: illegal operands `arcv.bitrev t6,t0,t3,t0'
.*: Error: illegal operands `arcv.bitrev 0,t3,t6'
.*: Error: illegal operands `arcv.bitrev t0,3,t6'
.*: Error: illegal operands `arcv.bitrev t0,t3,6'
