.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vqmxm8.vv v0,v3,v6', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8.vv v3,v6,v0', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8.vv v6,v0,v3', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8u.vv v0,v3,v6', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8u.vv v3,v6,v0', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8u.vv v6,v0,v3', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8su.vv v0,v3,v6', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8su.vv v3,v6,v0', extension `xarcvmxmc' required
.*: Error: unrecognized opcode `arcv.vqmxm8su.vv v6,v0,v3', extension `xarcvmxmc' required
.*: Error: illegal operands `arcv.vqmxm8.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm8.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm8.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm8u.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm8u.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm8u.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm8su.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm8su.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm8su.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm8.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm8.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm8.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm8u.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm8u.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm8u.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm8su.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm8su.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm8su.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm8.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm8.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm8.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm8u.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm8u.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm8u.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm8su.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm8su.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm8su.vv v0,v3,6'
