.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vqmxm4.vv v0,v3,v6', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4.vv v3,v6,v0', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4.vv v6,v0,v3', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4u.vv v0,v3,v6', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4u.vv v3,v6,v0', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4u.vv v6,v0,v3', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4su.vv v0,v3,v6', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4su.vv v3,v6,v0', extension `xarcvmxmb' required
.*: Error: unrecognized opcode `arcv.vqmxm4su.vv v6,v0,v3', extension `xarcvmxmb' required
.*: Error: illegal operands `arcv.vqmxm4.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm4.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm4.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm4u.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm4u.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm4u.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm4su.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm4su.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm4su.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm4.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm4.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm4.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm4u.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm4u.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm4u.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm4su.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm4su.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm4su.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm4.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm4.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm4.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm4u.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm4u.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm4u.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm4su.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm4su.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm4su.vv v0,v3,6'
