.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vqmxm16.vv v0,v3,v6', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16.vv v3,v6,v0', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16.vv v6,v0,v3', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16u.vv v0,v3,v6', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16u.vv v3,v6,v0', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16u.vv v6,v0,v3', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16su.vv v0,v3,v6', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16su.vv v3,v6,v0', extension `xarcvmxmd' required
.*: Error: unrecognized opcode `arcv.vqmxm16su.vv v6,v0,v3', extension `xarcvmxmd' required
.*: Error: illegal operands `arcv.vqmxm16.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm16.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm16.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm16u.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm16u.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm16u.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm16su.vv v0,v3'
.*: Error: illegal operands `arcv.vqmxm16su.vv v3,v6'
.*: Error: illegal operands `arcv.vqmxm16su.vv v6,v0'
.*: Error: illegal operands `arcv.vqmxm16.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm16.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm16.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm16u.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm16u.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm16u.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm16su.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqmxm16su.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqmxm16su.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqmxm16.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm16.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm16.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm16u.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm16u.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm16u.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqmxm16su.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqmxm16su.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqmxm16su.vv v0,v3,6'
