.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.vconj.v v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vconj.v v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vcmuli.v v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vcmuli.v v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vcmulni.v v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vcmulni.v v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.veven.v v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.veven.v v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vodd.v v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vodd.v v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vinterleave.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vinterleave.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vinterleave.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscredsum.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscredsum.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscredsum.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwcredsum.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwcredsum.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwcredsum.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscmul.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vscjmul.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmul.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmul.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscmac.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscnmsac.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjmac.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vs v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vs v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjnmsac.vs v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscrdot.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscrdot.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscrdot.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjrdot.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjrdot.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vwscjrdot.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcrdot.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcrdot.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcrdot.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcjrdot.vv v0,v3,v6', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcjrdot.vv v3,v6,v0', extension `xarcvvcplx' required
.*: Error: unrecognized opcode `arcv.vqcjrdot.vv v6,v0,v3', extension `xarcvvcplx' required
.*: Error: illegal operands `arcv.vconj.v v0'
.*: Error: illegal operands `arcv.vconj.v v3'
.*: Error: illegal operands `arcv.vcmuli.v v0'
.*: Error: illegal operands `arcv.vcmuli.v v3'
.*: Error: illegal operands `arcv.vcmulni.v v0'
.*: Error: illegal operands `arcv.vcmulni.v v3'
.*: Error: illegal operands `arcv.veven.v v0'
.*: Error: illegal operands `arcv.veven.v v3'
.*: Error: illegal operands `arcv.vodd.v v0'
.*: Error: illegal operands `arcv.vodd.v v3'
.*: Error: illegal operands `arcv.vinterleave.vv v0,v3'
.*: Error: illegal operands `arcv.vinterleave.vv v3,v6'
.*: Error: illegal operands `arcv.vinterleave.vv v6,v0'
.*: Error: illegal operands `arcv.vscredsum.vv v0,v3'
.*: Error: illegal operands `arcv.vscredsum.vv v3,v6'
.*: Error: illegal operands `arcv.vscredsum.vv v6,v0'
.*: Error: illegal operands `arcv.vwcredsum.vv v0,v3'
.*: Error: illegal operands `arcv.vwcredsum.vv v3,v6'
.*: Error: illegal operands `arcv.vwcredsum.vv v6,v0'
.*: Error: illegal operands `arcv.vscmul.vv v0,v3'
.*: Error: illegal operands `arcv.vscmul.vv v3,v6'
.*: Error: illegal operands `arcv.vscmul.vv v6,v0'
.*: Error: illegal operands `arcv.vscmul.vs v0,v3'
.*: Error: illegal operands `arcv.vscmul.vs v3,v6'
.*: Error: illegal operands `arcv.vscmul.vs v6,v0'
.*: Error: illegal operands `arcv.vscjmul.vv v0,v3'
.*: Error: illegal operands `arcv.vscjmul.vv v3,v6'
.*: Error: illegal operands `arcv.vscjmul.vv v6,v0'
.*: Error: illegal operands `arcv.vscjmul.vs v0,v3'
.*: Error: illegal operands `arcv.vscjmul.vs v3,v6'
.*: Error: illegal operands `arcv.vscjmul.vs v6,v0'
.*: Error: illegal operands `arcv.vwscmul.vv v0,v3'
.*: Error: illegal operands `arcv.vwscmul.vv v3,v6'
.*: Error: illegal operands `arcv.vwscmul.vv v6,v0'
.*: Error: illegal operands `arcv.vwscmul.vs v0,v3'
.*: Error: illegal operands `arcv.vwscmul.vs v3,v6'
.*: Error: illegal operands `arcv.vwscmul.vs v6,v0'
.*: Error: illegal operands `arcv.vwscjmul.vv v0,v3'
.*: Error: illegal operands `arcv.vwscjmul.vv v3,v6'
.*: Error: illegal operands `arcv.vwscjmul.vv v6,v0'
.*: Error: illegal operands `arcv.vwscjmul.vs v0,v3'
.*: Error: illegal operands `arcv.vwscjmul.vs v3,v6'
.*: Error: illegal operands `arcv.vwscjmul.vs v6,v0'
.*: Error: illegal operands `arcv.vwscmac.vv v0,v3'
.*: Error: illegal operands `arcv.vwscmac.vv v3,v6'
.*: Error: illegal operands `arcv.vwscmac.vv v6,v0'
.*: Error: illegal operands `arcv.vwscmac.vs v0,v3'
.*: Error: illegal operands `arcv.vwscmac.vs v3,v6'
.*: Error: illegal operands `arcv.vwscmac.vs v6,v0'
.*: Error: illegal operands `arcv.vwscnmsac.vv v0,v3'
.*: Error: illegal operands `arcv.vwscnmsac.vv v3,v6'
.*: Error: illegal operands `arcv.vwscnmsac.vv v6,v0'
.*: Error: illegal operands `arcv.vwscnmsac.vs v0,v3'
.*: Error: illegal operands `arcv.vwscnmsac.vs v3,v6'
.*: Error: illegal operands `arcv.vwscnmsac.vs v6,v0'
.*: Error: illegal operands `arcv.vwscjmac.vv v0,v3'
.*: Error: illegal operands `arcv.vwscjmac.vv v3,v6'
.*: Error: illegal operands `arcv.vwscjmac.vv v6,v0'
.*: Error: illegal operands `arcv.vwscjmac.vs v0,v3'
.*: Error: illegal operands `arcv.vwscjmac.vs v3,v6'
.*: Error: illegal operands `arcv.vwscjmac.vs v6,v0'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v0,v3'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v3,v6'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v6,v0'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v0,v3'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v3,v6'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v6,v0'
.*: Error: illegal operands `arcv.vwscrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vwscrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vwscrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vwscjrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vwscjrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vwscjrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vqcrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vqcrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vqcrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vqcjrdot.vv v0,v3'
.*: Error: illegal operands `arcv.vqcjrdot.vv v3,v6'
.*: Error: illegal operands `arcv.vqcjrdot.vv v6,v0'
.*: Error: illegal operands `arcv.vconj.v v0,v3,t0'
.*: Error: illegal operands `arcv.vconj.v v3,v6,t0'
.*: Error: illegal operands `arcv.vcmuli.v v0,v3,t0'
.*: Error: illegal operands `arcv.vcmuli.v v3,v6,t0'
.*: Error: illegal operands `arcv.vcmulni.v v0,v3,t0'
.*: Error: illegal operands `arcv.vcmulni.v v3,v6,t0'
.*: Error: illegal operands `arcv.veven.v v0,v3,t0'
.*: Error: illegal operands `arcv.veven.v v3,v6,t0'
.*: Error: illegal operands `arcv.vodd.v v0,v3,t0'
.*: Error: illegal operands `arcv.vodd.v v3,v6,t0'
.*: Error: illegal operands `arcv.vinterleave.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vinterleave.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vinterleave.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vscredsum.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vscredsum.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vscredsum.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwcredsum.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwcredsum.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwcredsum.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vscmul.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vscmul.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vscmul.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vscmul.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vscmul.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vscmul.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vscjmul.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vscjmul.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vscjmul.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vscjmul.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vscjmul.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vscjmul.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscmul.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscmul.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscmul.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscmul.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscmul.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscmul.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjmul.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjmul.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjmul.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjmul.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjmul.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjmul.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscmac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscmac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscmac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscmac.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscmac.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscmac.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscnmsac.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjmac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjmac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjmac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjmac.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjmac.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjmac.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vwscjrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vwscjrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vwscjrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqcrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqcrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqcrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vqcjrdot.vv v0,v3,v6,t0'
.*: Error: illegal operands `arcv.vqcjrdot.vv v3,v6,v0,t0'
.*: Error: illegal operands `arcv.vqcjrdot.vv v6,v0,v3,t0'
.*: Error: illegal operands `arcv.vconj.v 0,v3'
.*: Error: illegal operands `arcv.vconj.v v0,3'
.*: Error: illegal operands `arcv.vcmuli.v 0,v3'
.*: Error: illegal operands `arcv.vcmuli.v v0,3'
.*: Error: illegal operands `arcv.vcmulni.v 0,v3'
.*: Error: illegal operands `arcv.vcmulni.v v0,3'
.*: Error: illegal operands `arcv.veven.v 0,v3'
.*: Error: illegal operands `arcv.veven.v v0,3'
.*: Error: illegal operands `arcv.vodd.v 0,v3'
.*: Error: illegal operands `arcv.vodd.v v0,3'
.*: Error: illegal operands `arcv.vinterleave.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vinterleave.vv v0,3,v6'
.*: Error: illegal operands `arcv.vinterleave.vv v0,v3,6'
.*: Error: illegal operands `arcv.vscredsum.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vscredsum.vv v0,3,v6'
.*: Error: illegal operands `arcv.vscredsum.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwcredsum.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwcredsum.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwcredsum.vv v0,v3,6'
.*: Error: illegal operands `arcv.vscmul.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vscmul.vv v0,3,v6'
.*: Error: illegal operands `arcv.vscmul.vv v0,v3,6'
.*: Error: illegal operands `arcv.vscmul.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vscmul.vs v0,3,t6'
.*: Error: illegal operands `arcv.vscmul.vs v0,v3,6'
.*: Error: illegal operands `arcv.vscjmul.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vscjmul.vv v0,3,v6'
.*: Error: illegal operands `arcv.vscjmul.vv v0,v3,6'
.*: Error: illegal operands `arcv.vscjmul.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vscjmul.vs v0,3,t6'
.*: Error: illegal operands `arcv.vscjmul.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscmul.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscmul.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscmul.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscmul.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscmul.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscmul.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscjmul.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscjmul.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscjmul.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscjmul.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscjmul.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscjmul.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscmac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscmac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscmac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscmac.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscmac.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscmac.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscnmsac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscnmsac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscnmsac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscnmsac.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscnmsac.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscnmsac.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscjmac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscjmac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscjmac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscjmac.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscjmac.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscjmac.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscjnmsac.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscjnmsac.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscjnmsac.vs 0,v3,t6'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v0,3,t6'
.*: Error: illegal operands `arcv.vwscjnmsac.vs v0,v3,6'
.*: Error: illegal operands `arcv.vwscrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vwscjrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vwscjrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vwscjrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqcrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqcrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqcrdot.vv v0,v3,6'
.*: Error: illegal operands `arcv.vqcjrdot.vv 0,v3,v6'
.*: Error: illegal operands `arcv.vqcjrdot.vv v0,3,v6'
.*: Error: illegal operands `arcv.vqcjrdot.vv v0,v3,6'
