.*: Assembler messages:
.*:1: Error: unrecognized opcode `arcv.xvadd.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:2: Error: unrecognized opcode `arcv.xvadd.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:3: Error: unrecognized opcode `arcv.xvadd.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:5: Error: unrecognized opcode `arcv.xvsub.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:6: Error: unrecognized opcode `arcv.xvsub.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:7: Error: unrecognized opcode `arcv.xvsub.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:9: Error: unrecognized opcode `arcv.xvsadd.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:10: Error: unrecognized opcode `arcv.xvsadd.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:11: Error: unrecognized opcode `arcv.xvsadd.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:13: Error: unrecognized opcode `arcv.xvsadd.vv t0,t3,t6,e32,m1', extension `xarcvudsp' required
.*:14: Error: unrecognized opcode `arcv.xvsadd.vv t3,t6,t0,e32,m1', extension `xarcvudsp' required
.*:15: Error: unrecognized opcode `arcv.xvsadd.vv t6,t0,t3,e32,m1', extension `xarcvudsp' required
.*:17: Error: unrecognized opcode `arcv.xvssub.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:18: Error: unrecognized opcode `arcv.xvssub.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:19: Error: unrecognized opcode `arcv.xvssub.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:21: Error: unrecognized opcode `arcv.xvssub.vv t0,t3,t6,e32,m1', extension `xarcvudsp' required
.*:22: Error: unrecognized opcode `arcv.xvssub.vv t3,t6,t0,e32,m1', extension `xarcvudsp' required
.*:23: Error: unrecognized opcode `arcv.xvssub.vv t6,t0,t3,e32,m1', extension `xarcvudsp' required
.*:25: Error: unrecognized opcode `arcv.xvsll.vx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:26: Error: unrecognized opcode `arcv.xvsll.vx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:27: Error: unrecognized opcode `arcv.xvsll.vx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:29: Error: unrecognized opcode `arcv.xvsra.vx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:30: Error: unrecognized opcode `arcv.xvsra.vx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:31: Error: unrecognized opcode `arcv.xvsra.vx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:33: Error: unrecognized opcode `arcv.xvnclip.wx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:34: Error: unrecognized opcode `arcv.xvnclip.wx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:35: Error: unrecognized opcode `arcv.xvnclip.wx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:37: Error: unrecognized opcode `arcv.xvnclip.wx t0,t3,t6,e16,mf2', extension `xarcvudsp' required
.*:38: Error: unrecognized opcode `arcv.xvnclip.wx t3,t6,t0,e16,mf2', extension `xarcvudsp' required
.*:39: Error: unrecognized opcode `arcv.xvnclip.wx t6,t0,t3,e16,mf2', extension `xarcvudsp' required
.*:41: Error: unrecognized opcode `arcv.xvwmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:42: Error: unrecognized opcode `arcv.xvwmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:43: Error: unrecognized opcode `arcv.xvwmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:45: Error: unrecognized opcode `arcv.xvwmul.vv t0,t3,t6,e16,mf2', extension `xarcvudsp' required
.*:46: Error: unrecognized opcode `arcv.xvwmul.vv t3,t6,t0,e16,mf2', extension `xarcvudsp' required
.*:47: Error: unrecognized opcode `arcv.xvwmul.vv t6,t0,t3,e16,mf2', extension `xarcvudsp' required
.*:49: Error: unrecognized opcode `arcv.xvwsrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:50: Error: unrecognized opcode `arcv.xvwsrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:51: Error: unrecognized opcode `arcv.xvwsrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:53: Error: unrecognized opcode `arcv.xvscmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:54: Error: unrecognized opcode `arcv.xvscmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:55: Error: unrecognized opcode `arcv.xvscmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:57: Error: unrecognized opcode `arcv.xvscjmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:58: Error: unrecognized opcode `arcv.xvscjmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:59: Error: unrecognized opcode `arcv.xvscjmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:61: Error: unrecognized opcode `arcv.xvwscmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:62: Error: unrecognized opcode `arcv.xvwscmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:63: Error: unrecognized opcode `arcv.xvwscmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:65: Error: unrecognized opcode `arcv.xvwscjmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:66: Error: unrecognized opcode `arcv.xvwscjmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:67: Error: unrecognized opcode `arcv.xvwscjmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:69: Error: unrecognized opcode `arcv.xvwscrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:70: Error: unrecognized opcode `arcv.xvwscrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:71: Error: unrecognized opcode `arcv.xvwscrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:73: Error: unrecognized opcode `arcv.xvwscjrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*:74: Error: unrecognized opcode `arcv.xvwscjrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*:75: Error: unrecognized opcode `arcv.xvwscjrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*:77: Error: unrecognized opcode `arcv.bitrev t0,t3,t6', extension `xarcvudsp' required
.*:78: Error: unrecognized opcode `arcv.bitrev t3,t6,t0', extension `xarcvudsp' required
.*:79: Error: unrecognized opcode `arcv.bitrev t6,t0,t3', extension `xarcvudsp' required
.*:8: Error: `xarcvudsp' is conflict with the `v' extension
.*:11: Error: illegal operands `arcv.xvadd.vv t0,t3,5,e16,m1'
.*:12: Error: illegal operands `arcv.xvadd.vv t3,5,t0,e16,m1'
.*:13: Error: illegal operands `arcv.xvadd.vv 5,t0,t3,e16,m1'
.*:15: Error: illegal operands `arcv.xvsub.vv t0,t3,5,e16,m1'
.*:16: Error: illegal operands `arcv.xvsub.vv t3,5,t0,e16,m1'
.*:17: Error: illegal operands `arcv.xvsub.vv 5,t0,t3,e16,m1'
.*:19: Error: illegal operands `arcv.xvsadd.vv t0,t3,5,e16,m1'
.*:20: Error: illegal operands `arcv.xvsadd.vv t3,5,t0,e16,m1'
.*:21: Error: illegal operands `arcv.xvsadd.vv 5,t0,t3,e16,m1'
.*:23: Error: illegal operands `arcv.xvsadd.vv t0,t3,5,e32,m1'
.*:24: Error: illegal operands `arcv.xvsadd.vv t3,5,t0,e32,m1'
.*:25: Error: illegal operands `arcv.xvsadd.vv 5,t0,t3,e32,m1'
.*:27: Error: illegal operands `arcv.xvssub.vv t0,t3,5,e16,m1'
.*:28: Error: illegal operands `arcv.xvssub.vv t3,5,t0,e16,m1'
.*:29: Error: illegal operands `arcv.xvssub.vv 5,t0,t3,e16,m1'
.*:31: Error: illegal operands `arcv.xvssub.vv t0,t3,5,e32,m1'
.*:32: Error: illegal operands `arcv.xvssub.vv t3,5,t0,e32,m1'
.*:33: Error: illegal operands `arcv.xvssub.vv 5,t0,t3,e32,m1'
.*:35: Error: illegal operands `arcv.xvsll.vx t0,t3,5,e16,m1'
.*:36: Error: illegal operands `arcv.xvsll.vx t3,5,t0,e16,m1'
.*:37: Error: illegal operands `arcv.xvsll.vx 5,t0,t3,e16,m1'
.*:39: Error: illegal operands `arcv.xvsra.vx t0,t3,5,e16,m1'
.*:40: Error: illegal operands `arcv.xvsra.vx t3,5,t0,e16,m1'
.*:41: Error: illegal operands `arcv.xvsra.vx 5,t0,t3,e16,m1'
.*:43: Error: illegal operands `arcv.xvnclip.wx t0,t3,5,e16,m1'
.*:44: Error: illegal operands `arcv.xvnclip.wx t3,5,t0,e16,m1'
.*:45: Error: illegal operands `arcv.xvnclip.wx 5,t0,t3,e16,m1'
.*:47: Error: illegal operands `arcv.xvnclip.wx t0,t3,5,e16,mf2'
.*:48: Error: illegal operands `arcv.xvnclip.wx t3,5,t0,e16,mf2'
.*:49: Error: illegal operands `arcv.xvnclip.wx 5,t0,t3,e16,mf2'
.*:51: Error: illegal operands `arcv.xvwmul.vv t0,t3,5,e16,m1'
.*:52: Error: illegal operands `arcv.xvwmul.vv t3,5,t0,e16,m1'
.*:53: Error: illegal operands `arcv.xvwmul.vv 5,t0,t3,e16,m1'
.*:55: Error: illegal operands `arcv.xvwmul.vv t0,t3,5,e16,mf2'
.*:56: Error: illegal operands `arcv.xvwmul.vv t3,5,t0,e16,mf2'
.*:57: Error: illegal operands `arcv.xvwmul.vv 5,t0,t3,e16,mf2'
.*:59: Error: illegal operands `arcv.xvwsrdot.vv t0,t3,5,e16,m1'
.*:60: Error: illegal operands `arcv.xvwsrdot.vv t3,5,t0,e16,m1'
.*:61: Error: illegal operands `arcv.xvwsrdot.vv 5,t0,t3,e16,m1'
.*:63: Error: illegal operands `arcv.xvscmul.vv t0,t3,5,e16,m1'
.*:64: Error: illegal operands `arcv.xvscmul.vv t3,5,t0,e16,m1'
.*:65: Error: illegal operands `arcv.xvscmul.vv 5,t0,t3,e16,m1'
.*:67: Error: illegal operands `arcv.xvscjmul.vv t0,t3,5,e16,m1'
.*:68: Error: illegal operands `arcv.xvscjmul.vv t3,5,t0,e16,m1'
.*:69: Error: illegal operands `arcv.xvscjmul.vv 5,t0,t3,e16,m1'
.*:71: Error: illegal operands `arcv.xvwscmul.vv t0,t3,5,e16,m1'
.*:72: Error: illegal operands `arcv.xvwscmul.vv t3,5,t0,e16,m1'
.*:73: Error: illegal operands `arcv.xvwscmul.vv 5,t0,t3,e16,m1'
.*:75: Error: illegal operands `arcv.xvwscjmul.vv t0,t3,5,e16,m1'
.*:76: Error: illegal operands `arcv.xvwscjmul.vv t3,5,t0,e16,m1'
.*:77: Error: illegal operands `arcv.xvwscjmul.vv 5,t0,t3,e16,m1'
.*:79: Error: illegal operands `arcv.xvwscrdot.vv t0,t3,5,e16,m1'
.*:80: Error: illegal operands `arcv.xvwscrdot.vv t3,5,t0,e16,m1'
.*:81: Error: illegal operands `arcv.xvwscrdot.vv 5,t0,t3,e16,m1'
.*:83: Error: illegal operands `arcv.xvwscjrdot.vv t0,t3,5,e16,m1'
.*:84: Error: illegal operands `arcv.xvwscjrdot.vv t3,5,t0,e16,m1'
.*:85: Error: illegal operands `arcv.xvwscjrdot.vv 5,t0,t3,e16,m1'
.*:87: Error: illegal operands `arcv.bitrev t0,t3,5'
.*:88: Error: illegal operands `arcv.bitrev t3,5,t0'
.*:89: Error: illegal operands `arcv.bitrev 5,t0,t3'
.*:92: Error: bad ARC-V UDSP instruction: SEW not specified
.*:94: Error: bad ARC-V UDSP instruction: SEW not specified
.*:96: Error: bad ARC-V UDSP instruction: SEW not specified
.*:98: Error: bad ARC-V UDSP instruction: SEW not specified
.*:100: Error: bad ARC-V UDSP instruction: SEW not specified
.*:102: Error: bad ARC-V UDSP instruction: SEW not specified
.*:104: Error: bad ARC-V UDSP instruction: SEW not specified
.*:105: Error: bad ARC-V UDSP instruction: SEW not specified
.*:107: Error: bad ARC-V UDSP instruction: SEW not specified
.*:108: Error: bad ARC-V UDSP instruction: SEW not specified
.*:110: Error: bad ARC-V UDSP instruction: SEW not specified
.*:112: Error: bad ARC-V UDSP instruction: SEW not specified
.*:114: Error: bad ARC-V UDSP instruction: SEW not specified
.*:116: Error: bad ARC-V UDSP instruction: SEW not specified
.*:118: Error: bad ARC-V UDSP instruction: SEW not specified
.*:120: Error: bad ARC-V UDSP instruction: SEW not specified
.*:122: Error: bad ARC-V UDSP instruction: SEW not specified
.*:125: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:127: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:129: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:130: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:132: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:133: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:135: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:137: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:139: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:141: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:143: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:145: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:147: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:149: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:151: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:153: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:155: Error: bad ARC-V UDSP instruction: LMUL not specified
.*:159: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:160: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:161: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:162: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:164: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:165: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:166: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:167: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:169: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:170: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:171: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:173: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:174: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:175: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:177: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:178: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:179: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:180: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:182: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:183: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:184: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:185: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:187: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:188: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:189: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:191: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:192: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:193: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:195: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:196: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:197: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:198: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:200: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:201: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:202: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:203: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:205: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:206: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:207: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:208: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:210: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:211: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:212: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:213: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:215: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:216: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:217: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:218: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:220: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:221: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:222: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:223: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:225: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:226: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:227: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:228: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*:232: Error: illegal operands `arcv.xvadd.vv t0,t3,t6,e16,m1,tu'
.*:233: Error: illegal operands `arcv.xvadd.vv t3,t6,t0,e16,m1,tu'
.*:234: Error: illegal operands `arcv.xvadd.vv t6,t0,t3,e16,m1,tu'
.*:236: Error: illegal operands `arcv.xvsub.vv t0,t3,t6,e16,m1,tu'
.*:237: Error: illegal operands `arcv.xvsub.vv t3,t6,t0,e16,m1,tu'
.*:238: Error: illegal operands `arcv.xvsub.vv t6,t0,t3,e16,m1,tu'
.*:240: Error: illegal operands `arcv.xvsadd.vv t0,t3,t6,e16,m1,tu'
.*:241: Error: illegal operands `arcv.xvsadd.vv t3,t6,t0,e16,m1,tu'
.*:242: Error: illegal operands `arcv.xvsadd.vv t6,t0,t3,e16,m1,tu'
.*:244: Error: illegal operands `arcv.xvsadd.vv t0,t3,t6,e32,m1,tu'
.*:245: Error: illegal operands `arcv.xvsadd.vv t3,t6,t0,e32,m1,tu'
.*:246: Error: illegal operands `arcv.xvsadd.vv t6,t0,t3,e32,m1,tu'
.*:248: Error: illegal operands `arcv.xvssub.vv t0,t3,t6,e16,m1,tu'
.*:249: Error: illegal operands `arcv.xvssub.vv t3,t6,t0,e16,m1,tu'
.*:250: Error: illegal operands `arcv.xvssub.vv t6,t0,t3,e16,m1,tu'
.*:252: Error: illegal operands `arcv.xvssub.vv t0,t3,t6,e32,m1,tu'
.*:253: Error: illegal operands `arcv.xvssub.vv t3,t6,t0,e32,m1,tu'
.*:254: Error: illegal operands `arcv.xvssub.vv t6,t0,t3,e32,m1,tu'
.*:256: Error: illegal operands `arcv.xvsll.vx t0,t3,t6,e16,m1,tu'
.*:257: Error: illegal operands `arcv.xvsll.vx t3,t6,t0,e16,m1,tu'
.*:258: Error: illegal operands `arcv.xvsll.vx t6,t0,t3,e16,m1,tu'
.*:260: Error: illegal operands `arcv.xvsra.vx t0,t3,t6,e16,m1,tu'
.*:261: Error: illegal operands `arcv.xvsra.vx t3,t6,t0,e16,m1,tu'
.*:262: Error: illegal operands `arcv.xvsra.vx t6,t0,t3,e16,m1,tu'
.*:264: Error: illegal operands `arcv.xvnclip.wx t0,t3,t6,e16,m1,tu'
.*:265: Error: illegal operands `arcv.xvnclip.wx t3,t6,t0,e16,m1,tu'
.*:266: Error: illegal operands `arcv.xvnclip.wx t6,t0,t3,e16,m1,tu'
.*:268: Error: illegal operands `arcv.xvnclip.wx t0,t3,t6,e16,mf2,tu'
.*:269: Error: illegal operands `arcv.xvnclip.wx t3,t6,t0,e16,mf2,tu'
.*:270: Error: illegal operands `arcv.xvnclip.wx t6,t0,t3,e16,mf2,tu'
.*:272: Error: illegal operands `arcv.xvwmul.vv t0,t3,t6,e16,m1,tu'
.*:273: Error: illegal operands `arcv.xvwmul.vv t3,t6,t0,e16,m1,tu'
.*:274: Error: illegal operands `arcv.xvwmul.vv t6,t0,t3,e16,m1,tu'
.*:276: Error: illegal operands `arcv.xvwmul.vv t0,t3,t6,e16,mf2,tu'
.*:277: Error: illegal operands `arcv.xvwmul.vv t3,t6,t0,e16,mf2,tu'
.*:278: Error: illegal operands `arcv.xvwmul.vv t6,t0,t3,e16,mf2,tu'
.*:280: Error: illegal operands `arcv.xvwsrdot.vv t0,t3,t6,e16,m1,tu'
.*:281: Error: illegal operands `arcv.xvwsrdot.vv t3,t6,t0,e16,m1,tu'
.*:282: Error: illegal operands `arcv.xvwsrdot.vv t6,t0,t3,e16,m1,tu'
.*:284: Error: illegal operands `arcv.xvscmul.vv t0,t3,t6,e16,m1,tu'
.*:285: Error: illegal operands `arcv.xvscmul.vv t3,t6,t0,e16,m1,tu'
.*:286: Error: illegal operands `arcv.xvscmul.vv t6,t0,t3,e16,m1,tu'
.*:288: Error: illegal operands `arcv.xvscjmul.vv t0,t3,t6,e16,m1,tu'
.*:289: Error: illegal operands `arcv.xvscjmul.vv t3,t6,t0,e16,m1,tu'
.*:290: Error: illegal operands `arcv.xvscjmul.vv t6,t0,t3,e16,m1,tu'
.*:292: Error: illegal operands `arcv.xvwscmul.vv t0,t3,t6,e16,m1,tu'
.*:293: Error: illegal operands `arcv.xvwscmul.vv t3,t6,t0,e16,m1,tu'
.*:294: Error: illegal operands `arcv.xvwscmul.vv t6,t0,t3,e16,m1,tu'
.*:296: Error: illegal operands `arcv.xvwscjmul.vv t0,t3,t6,e16,m1,tu'
.*:297: Error: illegal operands `arcv.xvwscjmul.vv t3,t6,t0,e16,m1,tu'
.*:298: Error: illegal operands `arcv.xvwscjmul.vv t6,t0,t3,e16,m1,tu'
.*:300: Error: illegal operands `arcv.xvwscrdot.vv t0,t3,t6,e16,m1,tu'
.*:301: Error: illegal operands `arcv.xvwscrdot.vv t3,t6,t0,e16,m1,tu'
.*:302: Error: illegal operands `arcv.xvwscrdot.vv t6,t0,t3,e16,m1,tu'
.*:304: Error: illegal operands `arcv.xvwscjrdot.vv t0,t3,t6,e16,m1,tu'
.*:305: Error: illegal operands `arcv.xvwscjrdot.vv t3,t6,t0,e16,m1,tu'
.*:306: Error: illegal operands `arcv.xvwscjrdot.vv t6,t0,t3,e16,m1,tu'
