.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.bspeek t0,t3', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspeek t3,t6', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspop t0,t3', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspop t3,t6', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspush t0,t3,t6', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspush t3,t6,t0', extension `xarcvbitstream' required
.*: Error: unrecognized opcode `arcv.bspush t6,t0,t3', extension `xarcvbitstream' required
.*: Error: illegal operands `arcv.bspeek t0'
.*: Error: illegal operands `arcv.bspeek t3'
.*: Error: illegal operands `arcv.bspop t0'
.*: Error: illegal operands `arcv.bspop t3'
.*: Error: illegal operands `arcv.bspush t0,t3'
.*: Error: illegal operands `arcv.bspush t3,t6'
.*: Error: illegal operands `arcv.bspush t6,t0'
.*: Error: illegal operands `arcv.bspeek t0,t3,t0'
.*: Error: illegal operands `arcv.bspeek t3,t6,t0'
.*: Error: illegal operands `arcv.bspop t0,t3,t0'
.*: Error: illegal operands `arcv.bspop t3,t6,t0'
.*: Error: illegal operands `arcv.bspush t0,t3,t6,t0'
.*: Error: illegal operands `arcv.bspush t3,t6,t0,t0'
.*: Error: illegal operands `arcv.bspush t6,t0,t3,t0'
.*: Error: illegal operands `arcv.bspeek 0,t3'
.*: Error: illegal operands `arcv.bspeek t0,3'
.*: Error: illegal operands `arcv.bspop 0,t3'
.*: Error: illegal operands `arcv.bspop t0,3'
.*: Error: illegal operands `arcv.bspush 0,t3,t6'
.*: Error: illegal operands `arcv.bspush t0,3,t6'
.*: Error: illegal operands `arcv.bspush t0,t3,6'
