.*: Assembler messages:
.*: Error: unrecognized opcode `arcv.xvadd.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvadd.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvadd.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsub.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsub.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsub.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t0,t3,t6,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t3,t6,t0,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsadd.vv t6,t0,t3,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t0,t3,t6,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t3,t6,t0,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvssub.vv t6,t0,t3,e32,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsll.vx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsll.vx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsll.vx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsra.vx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsra.vx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvsra.vx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t0,t3,t6,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t3,t6,t0,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvnclip.wx t6,t0,t3,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t0,t3,t6,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t3,t6,t0,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwmul.vv t6,t0,t3,e16,mf2', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwsrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwsrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwsrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscjmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscjmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvscjmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjmul.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjmul.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjmul.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjrdot.vv t0,t3,t6,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjrdot.vv t3,t6,t0,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.xvwscjrdot.vv t6,t0,t3,e16,m1', extension `xarcvudsp' required
.*: Error: unrecognized opcode `arcv.bitrev t0,t3,t6', extension `xarcvbitrev' required
.*: Error: unrecognized opcode `arcv.bitrev t3,t6,t0', extension `xarcvbitrev' required
.*: Error: unrecognized opcode `arcv.bitrev t6,t0,t3', extension `xarcvbitrev' required
.*: Error: `xarcvudsp' is conflict with the `v' extension
.*: Error: illegal operands `arcv.xvadd.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvadd.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvadd.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvsub.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvsub.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvsub.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvsadd.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvsadd.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvsadd.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvsadd.vv t0,t3,5,e32,m1'
.*: Error: illegal operands `arcv.xvsadd.vv t3,5,t0,e32,m1'
.*: Error: illegal operands `arcv.xvsadd.vv 5,t0,t3,e32,m1'
.*: Error: illegal operands `arcv.xvssub.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvssub.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvssub.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvssub.vv t0,t3,5,e32,m1'
.*: Error: illegal operands `arcv.xvssub.vv t3,5,t0,e32,m1'
.*: Error: illegal operands `arcv.xvssub.vv 5,t0,t3,e32,m1'
.*: Error: illegal operands `arcv.xvsll.vx t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvsll.vx t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvsll.vx 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvsra.vx t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvsra.vx t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvsra.vx 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvnclip.wx t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvnclip.wx t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvnclip.wx 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvnclip.wx t0,t3,5,e16,mf2'
.*: Error: illegal operands `arcv.xvnclip.wx t3,5,t0,e16,mf2'
.*: Error: illegal operands `arcv.xvnclip.wx 5,t0,t3,e16,mf2'
.*: Error: illegal operands `arcv.xvwmul.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwmul.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwmul.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvwmul.vv t0,t3,5,e16,mf2'
.*: Error: illegal operands `arcv.xvwmul.vv t3,5,t0,e16,mf2'
.*: Error: illegal operands `arcv.xvwmul.vv 5,t0,t3,e16,mf2'
.*: Error: illegal operands `arcv.xvwsrdot.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwsrdot.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwsrdot.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvscmul.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvscmul.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvscmul.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvscjmul.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvscjmul.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvscjmul.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvwscmul.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwscmul.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwscmul.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvwscjmul.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwscjmul.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwscjmul.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvwscrdot.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwscrdot.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwscrdot.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.xvwscjrdot.vv t0,t3,5,e16,m1'
.*: Error: illegal operands `arcv.xvwscjrdot.vv t3,5,t0,e16,m1'
.*: Error: illegal operands `arcv.xvwscjrdot.vv 5,t0,t3,e16,m1'
.*: Error: illegal operands `arcv.bitrev t0,t3,5'
.*: Error: illegal operands `arcv.bitrev t3,5,t0'
.*: Error: illegal operands `arcv.bitrev 5,t0,t3'
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: SEW not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: LMUL not specified
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: bad ARC-V UDSP instruction: combination of SEW and LMUL not supported for opcode
.*: Error: illegal operands `arcv.xvadd.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvadd.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvadd.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsub.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsub.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsub.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t0,t3,t6,e32,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t3,t6,t0,e32,m1,tu'
.*: Error: illegal operands `arcv.xvsadd.vv t6,t0,t3,e32,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t0,t3,t6,e32,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t3,t6,t0,e32,m1,tu'
.*: Error: illegal operands `arcv.xvssub.vv t6,t0,t3,e32,m1,tu'
.*: Error: illegal operands `arcv.xvsll.vx t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsll.vx t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsll.vx t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsra.vx t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsra.vx t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvsra.vx t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t0,t3,t6,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t3,t6,t0,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvnclip.wx t6,t0,t3,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t0,t3,t6,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t3,t6,t0,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvwmul.vv t6,t0,t3,e16,mf2,tu'
.*: Error: illegal operands `arcv.xvwsrdot.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwsrdot.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwsrdot.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscmul.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscmul.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscmul.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscjmul.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscjmul.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvscjmul.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscmul.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscmul.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscmul.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjmul.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjmul.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjmul.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscrdot.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscrdot.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscrdot.vv t6,t0,t3,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjrdot.vv t0,t3,t6,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjrdot.vv t3,t6,t0,e16,m1,tu'
.*: Error: illegal operands `arcv.xvwscjrdot.vv t6,t0,t3,e16,m1,tu'
