.*: Assembler messages:
.*: Error: Integer operand out of range; should be between -128 to 127, inclusive
.*: Error: Integer operand out of range; should be between -128 to 127, inclusive
.*: Error: Integer operand out of range; should be between -2048 to 2047, inclusive
.*: Error: Integer operand out of range; should be between -2048 to 2047, inclusive
.*: Error: Integer operand out of range; should be between -2048 to 2047, inclusive
.*: Error: Integer operand out of range; should be between -2048 to 2047, inclusive
