.*: Assembler messages:
.*: Error: unrecognized opcode `mips.fsinhz.s ft0,ft1', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.fcoshz.s ft2,ft3', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.ftanhz.s ft4,ft5', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.fversinhz.s ft6,ft7', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.fatanhz.s ft8,ft9', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.flti.s fa0,0', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.flti.s fa1,31', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.fftanh.s fs0,fs1', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.fflog2.s fs2,fs3', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.ffexp2.s fs4,fs5', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.ffrecip.s fs6,fs7', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.ffsqrt.s fs8,fs9', extension `xmipstrig' required
.*: Error: unrecognized opcode `mips.ffrsqrt.s fs10,fs11', extension `xmipstrig' required
.*: Error: illegal operands `mips.fsinhz.s ft0,ft1,ft2'
.*: Error: illegal operands `mips.fcoshz.s ft2,ft3,ft1'
.*: Error: illegal operands `mips.ftanhz.s ft4,ft5,ft0'
.*: Error: illegal operands `mips.fversinhz.s ft6,ft7,ft1'
.*: Error: illegal operands `mips.fatanhz.s ft8,ft9,ft0'
.*: Error: illegal operands `mips.flti.s fa0,0,9'
.*: Error: illegal operands `mips.fftanh.s fs0,fs1,fs2'
.*: Error: illegal operands `mips.fflog2.s fs2,fs3,fs0'
.*: Error: illegal operands `mips.ffexp2.s fs4,fs5,fs1'
.*: Error: illegal operands `mips.ffrecip.s fs6,fs7,fs6'
.*: Error: illegal operands `mips.ffsqrt.s fs8,fs9,fs0'
.*: Error: illegal operands `mips.ffrsqrt.s fs10,fs11,fs0'
.*: Error: improper CSRxI immediate \(32\)
