2012-12-06  Simon Cook  <simon.cook@embecosm.com>

	* opcode/arc.h: Change opcode syntax strings to be unsigned.

2012-12-04  Simon Cook  <simon.cook@embecosm.com>

	* opcode/arc.h: Support for non-@ operand types.

2010-08-19  Michael Eager <eager@eagercon.com>

	* elf.h: Define E_ARC_MACH_ARC601 = 4.

14  Irfan Rafiq  <irfan.rafiq@arc.com>
        * dis-asm.h (arc_get_disassembler) Update prototype.
