2013-10-01  Anton Kolesov  <akolesov@synopsys.com>

	* gdb.base/float.exp: Adjust expected output for ARC in "info float"
	test.

2013-09-11  Anton Kolesov  <akolesov@synopsys.com>

	* gdb.arch/arc-em-prologue.exp: Add a test case that GDB properly
	parses EM function prologue with -O0.
	* gdb.arch/arc-em-prologue.c: Source code for a test case above.

2013-03-25  Jeremy Bennett  <jeremy.bennett@embecosm.com>

	* gdb.base/float.exp: Add "info float" test for ARC.
